ipfsUrl: https://ipfs.infura.io:5001
soterUrl: https://sandbox.btfssoter.io
privateKey: c8f0884e706c761e80a9227736a4a595f56b43660041920a5e6765a9b8ac3ab7
userAddress: TTCXimHXjen9BdTFW5JvcLKGWNm3SSuECF
batchSize: 3
logger:
  path: .
  level: debug